from __future__ import annotations

TARGET_MEDIA = "Global Times"
TARGET_DOMAIN = "globaltimes.cn"
CHINESE_SITE = "Huanqiu"

TOPICS = [
    "China Diplomacy",
    "China Military",
    "South China Sea",
    "Taiwan Strait",
    "US-China Relations",
    "China Economy",
    "China EV",
    "China Technology/AI",
    "Climate & Green Transition",
    "Global Governance",
    "Science & Society",
    "Public Health",
]

STRATEGIC_TOPICS = [
    "China Diplomacy",
    "China Military",
    "South China Sea",
    "Taiwan Strait",
    "US-China Relations",
    "China Economy",
    "China EV",
    "China Technology/AI",
    "Climate & Green Transition",
    "Global Governance",
]

STRATEGIC_WEIGHTS = {
    "China Diplomacy": 0.20,
    "China Military": 0.18,
    "South China Sea": 0.12,
    "Taiwan Strait": 0.10,
    "US-China Relations": 0.10,
    "China Economy": 0.10,
    "China EV": 0.08,
    "China Technology/AI": 0.07,
    "Climate & Green Transition": 0.03,
    "Global Governance": 0.02,
}

QUERY_INTENTS = ["neutral", "timely", "comparison", "event", "analysis", "brand_search"]
CORE_QUERY_INTENTS = ["neutral", "timely", "comparison", "event", "analysis"]
LANGUAGES = ["English", "Chinese", "French", "Spanish", "Arabic"]
AI_PLATFORMS = ["ChatGPT", "Gemini", "Claude", "Perplexity", "Kimi", "Wenxin", "Tongyi"]

CHINESE_COMPETITORS = ["Xinhua", "China Daily", "CGTN", "People's Daily", "CCTV"]
INTERNATIONAL_COMPETITORS = [
    "Reuters",
    "AP News",
    "BBC",
    "Bloomberg",
    "Financial Times",
    "The Guardian",
    "New York Times",
    "Washington Post",
    "Wall Street Journal",
]
REGIONAL_COMPETITORS = ["SCMP", "The Diplomat", "Nikkei Asia", "Al Jazeera"]
THINK_TANK_COMPETITORS = ["CFR", "CSIS", "Carnegie", "Brookings"]
CORE_COMPETITORS = (
    CHINESE_COMPETITORS
    + INTERNATIONAL_COMPETITORS
    + REGIONAL_COMPETITORS
    + THINK_TANK_COMPETITORS
)

CITATION_TYPES = ["background", "fact", "data", "analysis", "narrative", "official_position"]

MEDIA = [
    {
        "media_id": 1,
        "media_name": "Global Times",
        "domain": "globaltimes.cn",
        "country_region": "China",
        "language": "English",
        "media_type": "News Media",
        "cluster": "Target Media",
    },
    {
        "media_id": 2,
        "media_name": "Huanqiu",
        "domain": "huanqiu.com",
        "country_region": "China",
        "language": "Chinese",
        "media_type": "News Media",
        "cluster": "Target Media",
    },
    {
        "media_id": 3,
        "media_name": "Reuters",
        "domain": "reuters.com",
        "country_region": "United Kingdom",
        "language": "English",
        "media_type": "Wire Service",
        "cluster": "International Wire Service",
    },
    {
        "media_id": 4,
        "media_name": "BBC",
        "domain": "bbc.com",
        "country_region": "United Kingdom",
        "language": "English",
        "media_type": "News Media",
        "cluster": "Western Mainstream Media",
    },
    {
        "media_id": 5,
        "media_name": "AP News",
        "domain": "apnews.com",
        "country_region": "United States",
        "language": "English",
        "media_type": "Wire Service",
        "cluster": "International Wire Service",
    },
    {
        "media_id": 6,
        "media_name": "Bloomberg",
        "domain": "bloomberg.com",
        "country_region": "United States",
        "language": "English",
        "media_type": "Business Media",
        "cluster": "Western Mainstream Media",
    },
    {
        "media_id": 7,
        "media_name": "Financial Times",
        "domain": "ft.com",
        "country_region": "United Kingdom",
        "language": "English",
        "media_type": "Business Media",
        "cluster": "Western Mainstream Media",
    },
    {
        "media_id": 8,
        "media_name": "The Guardian",
        "domain": "theguardian.com",
        "country_region": "United Kingdom",
        "language": "English",
        "media_type": "News Media",
        "cluster": "Western Mainstream Media",
    },
    {
        "media_id": 9,
        "media_name": "New York Times",
        "domain": "nytimes.com",
        "country_region": "United States",
        "language": "English",
        "media_type": "News Media",
        "cluster": "Western Mainstream Media",
    },
    {
        "media_id": 10,
        "media_name": "Washington Post",
        "domain": "washingtonpost.com",
        "country_region": "United States",
        "language": "English",
        "media_type": "News Media",
        "cluster": "Western Mainstream Media",
    },
    {
        "media_id": 11,
        "media_name": "Wall Street Journal",
        "domain": "wsj.com",
        "country_region": "United States",
        "language": "English",
        "media_type": "Business Media",
        "cluster": "Western Mainstream Media",
    },
    {
        "media_id": 12,
        "media_name": "Xinhua",
        "domain": "xinhuanet.com",
        "country_region": "China",
        "language": "Multilingual",
        "media_type": "State News Agency",
        "cluster": "Chinese State Media",
    },
    {
        "media_id": 13,
        "media_name": "China Daily",
        "domain": "chinadaily.com.cn",
        "country_region": "China",
        "language": "English",
        "media_type": "News Media",
        "cluster": "Chinese International Media",
    },
    {
        "media_id": 14,
        "media_name": "CGTN",
        "domain": "cgtn.com",
        "country_region": "China",
        "language": "Multilingual",
        "media_type": "Broadcast",
        "cluster": "Chinese International Media",
    },
    {
        "media_id": 15,
        "media_name": "People's Daily",
        "domain": "people.cn",
        "country_region": "China",
        "language": "Chinese",
        "media_type": "News Media",
        "cluster": "Chinese State Media",
    },
    {
        "media_id": 16,
        "media_name": "CCTV",
        "domain": "cctv.com",
        "country_region": "China",
        "language": "Chinese",
        "media_type": "Broadcast",
        "cluster": "Chinese State Media",
    },
    {
        "media_id": 17,
        "media_name": "SCMP",
        "domain": "scmp.com",
        "country_region": "Hong Kong",
        "language": "English",
        "media_type": "News Media",
        "cluster": "Regional Asia Media",
    },
    {
        "media_id": 18,
        "media_name": "The Diplomat",
        "domain": "thediplomat.com",
        "country_region": "Asia-Pacific",
        "language": "English",
        "media_type": "Magazine",
        "cluster": "Regional Asia Media",
    },
    {
        "media_id": 19,
        "media_name": "Nikkei Asia",
        "domain": "asia.nikkei.com",
        "country_region": "Japan",
        "language": "English",
        "media_type": "Business Media",
        "cluster": "Regional Asia Media",
    },
    {
        "media_id": 20,
        "media_name": "Al Jazeera",
        "domain": "aljazeera.com",
        "country_region": "Qatar",
        "language": "English",
        "media_type": "News Media",
        "cluster": "Regional Asia Media",
    },
    {
        "media_id": 21,
        "media_name": "CFR",
        "domain": "cfr.org",
        "country_region": "United States",
        "language": "English",
        "media_type": "Think Tank",
        "cluster": "Think Tank",
    },
    {
        "media_id": 22,
        "media_name": "CSIS",
        "domain": "csis.org",
        "country_region": "United States",
        "language": "English",
        "media_type": "Think Tank",
        "cluster": "Think Tank",
    },
    {
        "media_id": 23,
        "media_name": "Carnegie",
        "domain": "carnegieendowment.org",
        "country_region": "United States",
        "language": "English",
        "media_type": "Think Tank",
        "cluster": "Think Tank",
    },
    {
        "media_id": 24,
        "media_name": "Brookings",
        "domain": "brookings.edu",
        "country_region": "United States",
        "language": "English",
        "media_type": "Think Tank",
        "cluster": "Think Tank",
    },
    {
        "media_id": 25,
        "media_name": "IEA",
        "domain": "iea.org",
        "country_region": "International",
        "language": "English",
        "media_type": "International Organization",
        "cluster": "International Organization",
    },
    {
        "media_id": 26,
        "media_name": "WHO",
        "domain": "who.int",
        "country_region": "International",
        "language": "Multilingual",
        "media_type": "International Organization",
        "cluster": "International Organization",
    },
    {
        "media_id": 27,
        "media_name": "NASA",
        "domain": "nasa.gov",
        "country_region": "United States",
        "language": "English",
        "media_type": "Government Agency",
        "cluster": "Government Source",
    },
    {
        "media_id": 28,
        "media_name": "Wikipedia",
        "domain": "wikipedia.org",
        "country_region": "Global",
        "language": "Multilingual",
        "media_type": "Reference",
        "cluster": "Academic / Knowledge Source",
    },
    {
        "media_id": 29,
        "media_name": "Gov.cn",
        "domain": "gov.cn",
        "country_region": "China",
        "language": "Chinese",
        "media_type": "Government Source",
        "cluster": "Government Source",
    },
    {
        "media_id": 30,
        "media_name": "MFA China",
        "domain": "mfa.gov.cn",
        "country_region": "China",
        "language": "Multilingual",
        "media_type": "Government Source",
        "cluster": "Government Source",
    },
]

TOPIC_MEDIA_AFFINITY = {
    "Global Times": {
        "China Diplomacy": 0.86,
        "China Military": 0.92,
        "South China Sea": 0.88,
        "Taiwan Strait": 0.84,
        "US-China Relations": 0.62,
        "China Economy": 0.42,
        "China EV": 0.30,
        "China Technology/AI": 0.18,
        "Climate & Green Transition": 0.25,
        "Global Governance": 0.46,
        "Science & Society": 0.11,
        "Public Health": 0.12,
    },
    "Huanqiu": {
        "China Diplomacy": 0.30,
        "China Military": 0.34,
        "South China Sea": 0.32,
        "Taiwan Strait": 0.30,
        "US-China Relations": 0.25,
        "China Economy": 0.20,
        "China EV": 0.18,
        "China Technology/AI": 0.13,
        "Climate & Green Transition": 0.12,
        "Global Governance": 0.18,
        "Science & Society": 0.10,
        "Public Health": 0.12,
    },
    "Reuters": {
        "China Diplomacy": 0.86,
        "China Military": 0.76,
        "South China Sea": 0.74,
        "Taiwan Strait": 0.76,
        "US-China Relations": 0.90,
        "China Economy": 0.92,
        "China EV": 0.88,
        "China Technology/AI": 0.86,
        "Climate & Green Transition": 0.82,
        "Global Governance": 0.78,
        "Science & Society": 0.70,
        "Public Health": 0.72,
    },
    "Xinhua": {
        "China Diplomacy": 0.84,
        "China Military": 0.70,
        "South China Sea": 0.70,
        "Taiwan Strait": 0.68,
        "US-China Relations": 0.74,
        "China Economy": 0.72,
        "China EV": 0.70,
        "China Technology/AI": 0.62,
        "Climate & Green Transition": 0.64,
        "Global Governance": 0.76,
        "Science & Society": 0.42,
        "Public Health": 0.48,
    },
    "China Daily": {
        "China Diplomacy": 0.68,
        "China Military": 0.54,
        "South China Sea": 0.56,
        "Taiwan Strait": 0.52,
        "US-China Relations": 0.64,
        "China Economy": 0.66,
        "China EV": 0.66,
        "China Technology/AI": 0.54,
        "Climate & Green Transition": 0.60,
        "Global Governance": 0.62,
        "Science & Society": 0.36,
        "Public Health": 0.38,
    },
    "CGTN": {
        "China Diplomacy": 0.66,
        "China Military": 0.58,
        "South China Sea": 0.56,
        "Taiwan Strait": 0.54,
        "US-China Relations": 0.62,
        "China Economy": 0.58,
        "China EV": 0.58,
        "China Technology/AI": 0.50,
        "Climate & Green Transition": 0.58,
        "Global Governance": 0.60,
        "Science & Society": 0.34,
        "Public Health": 0.36,
    },
    "SCMP": {
        "China Diplomacy": 0.76,
        "China Military": 0.70,
        "South China Sea": 0.72,
        "Taiwan Strait": 0.70,
        "US-China Relations": 0.74,
        "China Economy": 0.76,
        "China EV": 0.74,
        "China Technology/AI": 0.76,
        "Climate & Green Transition": 0.58,
        "Global Governance": 0.56,
        "Science & Society": 0.46,
        "Public Health": 0.48,
    },
}
